config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :portfolios, expect: [:show]
  get "angular-items", to: "portfolios#angular"
  get 'portfolio/:id', to: "portfolios#show", as: 'portfolio_show'
  get 'about', to: "page#about"
  get "contact", to: 'page#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "page#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: ->(attrs) { attrs["name"].blank? }
  validates_presence_of :title, :subtitle, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: "Angular")
  end

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= "http://placehold.it/600x400"
    self.thumb_image ||= "http://placehold.it/300x250"
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: { except: [:destroy, :new, :create, :update, :edit] }, site_admin: :all

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    # loook what to destroy
    @portfolio_item = Portfolio.find(params[:id])
    # destroys
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<h1> Create New Portfolio</h1>

<%= form_for(@portfolio_item) do |f| %>

<div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
</div>


<div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
</div>

<div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
</div>
<ul>
    <%=f.fields_for :technologies do |technology_form| %>
    <li>

        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
    </li>
    <%end%>
</ul>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<p> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%> </p>
<p> <%= portfolio_item.subtitle%> </p>
<p> <%= portfolio_item.body%> </p>
<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:side_admin) %>
<%= link_to 'Delete', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:side_admin)%>

app/views/portfolios/angular.html.erb
<h1>Angular Items </h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:side_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
<p> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%> </p>
<p> <%= portfolio_item.subtitle%> </p>
<p> <%= portfolio_item.body%> </p>
<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:side_admin) %>
<%= link_to 'Delete', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:side_admin) %>
<%end%>

app/views/portfolios/edit.html.erb
<%= render 'form', portfolio_item: @portfolio_item%>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<%= render 'form', portfolio_item: @portfolio_item%>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>
<h1><%= @portfolio_item.title%></h1>

<em><%= @portfolio_item.subtitle%></em>

<p> <%= @portfolio_item.body%> </p>

<h2>Technology Used:<h2>
        <% @portfolio_item.technologies.each do |t| %>
        <p> <%= t.name %> </p>
        <%end%>